#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
import subprocess
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
RUN_SNIPER = ROOT / "snipersim" / "run-sniper"
DEFAULT_OUTPUT_DIR = ROOT / "asi-output"
DEFAULT_CORE_MODEL = "nehalem"
DEFAULT_CORE_TYPE = "rob"
DEFAULT_FREQUENCY = 2.66
DEFAULT_LOGICAL_CPUS = 1
DEFAULT_L1I_SIZE = 32
DEFAULT_L1D_SIZE = 32
DEFAULT_L2_SIZE = 256
DEFAULT_L3_SIZE = 8192
DEFAULT_L1I_ASSOC = 4
DEFAULT_L1D_ASSOC = 8
DEFAULT_L2_ASSOC = 8
DEFAULT_L3_ASSOC = 16
DEFAULT_BRANCH_PREDICTOR_TYPE = "pentium_m"
DEFAULT_BRANCH_MISPREDICT_PENALTY = 8
DEFAULT_BRANCH_PREDICTOR_SIZE = 1024

# Alpha controls the area/power trade-off in the ASI formula
DEFAULT_ALPHA = 0.5

# Search space: for each parameter, the candidate values to try.
PARAM_SPACE: dict[str, list[Any]] = {
    "l1i_size":                 [16, 32, 64],
    "l1d_size":                 [16, 32, 64],
    "l2_size":                  [128, 256, 512],
    "l3_size":                  [1024, 2048, 4096, 8192],
    "l1i_assoc":                [4, 8],
    "l1d_assoc":                [4, 8],
    "l2_assoc":                 [4, 8],
    "l3_assoc":                 [8, 16],
    "branch_predictor_size":    [512, 1024, 2048],
}


@dataclass
class DesignPoint:
    """One evaluated design point."""
    params: dict[str, Any]          # overrides from SEARCH_SPACE
    area: float                     # mm^2
    peak_power: float               # W
    time: float                     # ns
    asi: float = 0.0                # computed after baseline is known
    speedup: float = 0.0            # computed after baseline is known
    modified_params: set[str] = field(default_factory=set)



# y: the reference design
# x: the design under test
def calculate_asi(Ay: float, Ax: float, Py: float, Px: float, alpha: float) -> float:
    return (1 - alpha * (Ax / Ay)) / ((1 - alpha) * (Px / Py))


def dominates(a: DesignPoint, b: DesignPoint) -> bool:
    """Return True if a dominates b (better or equal on both, strictly better on at least one)."""
    return (
        a.asi >= b.asi and a.speedup >= b.speedup
        and (a.asi > b.asi or a.speedup > b.speedup)
    )


def update_pareto_front(front: list[DesignPoint], points: list[DesignPoint]) -> list[DesignPoint]:
    """Recompute the Pareto front from front + candidates combined."""
    all_points = front + points
    return [
        p for p in all_points
        if not any(dominates(other, p) for other in all_points if other is not p)
    ]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="asi.py",
        description="Algorithm launcher for design space exploration.",
    )
    parser.add_argument("--config", required=True, help="Reference design config file for Sniper.")
    parser.add_argument("--sniper", default=str(RUN_SNIPER), help="Path to the run-sniper entry point.")
    parser.add_argument("--outputdir", "-d", default=str(DEFAULT_OUTPUT_DIR), help="Output directory.")
    parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA, help="Alpha for ASI formula.")
    parser.add_argument("--show-config", action="store_true", help="Print config and exit.")
    parser.add_argument("cmd", nargs=argparse.REMAINDER, help="Command to run after --.")
    return parser


def build_runtime_config(
    reference_config: str,
    *,
    cores: int = None,
    core_model: str = None,
    core_type: str = None,
    frequency: float = None,
    logical_cpus: int = None,
    l1i_size: int = None,
    l1i_assoc: int = None,
    l1d_size: int = None,
    l1d_assoc: int = None,
    l2_size: int = None,
    l2_assoc: int = None,
    l3_size: int = None,
    l3_assoc: int = None,
    branch_predictor_type: str = None,
    branch_mispredict_penalty: int = None,
    branch_predictor_size: int = None,
) -> str:
    return "\n".join([
        "# Auto-generated by framework/asi.py",
        "#include base",
        "#include gainestown",
        "#include rob",
        f"# Reference config: {reference_config}",
        "",
        "[general]",
        f"total_cores = {cores or 1}",
        "",
        "[perf_model/core]",
        f"core_model = {core_model or DEFAULT_CORE_MODEL}",
        f"type = {core_type or DEFAULT_CORE_TYPE}",
        f"frequency = {frequency or DEFAULT_FREQUENCY}",
        f"logical_cpus = {logical_cpus or DEFAULT_LOGICAL_CPUS}",
        "",
        "[perf_model/l1_icache]",
        f"cache_size = {l1i_size or DEFAULT_L1I_SIZE}",
        f"associativity = {l1i_assoc or DEFAULT_L1I_ASSOC}",
        "",
        "[perf_model/l1_dcache]",
        f"cache_size = {l1d_size or DEFAULT_L1D_SIZE}",
        f"associativity = {l1d_assoc or DEFAULT_L1D_ASSOC}",
        "",
        "[perf_model/l2_cache]",
        f"cache_size = {l2_size or DEFAULT_L2_SIZE}",
        f"associativity = {l2_assoc or DEFAULT_L2_ASSOC}",
        "",
        "[perf_model/l3_cache]",
        f"cache_size = {l3_size or DEFAULT_L3_SIZE}",
        f"associativity = {l3_assoc or DEFAULT_L3_ASSOC}",
        "",
        "[perf_model/branch_predictor]",
        f"type = {branch_predictor_type or DEFAULT_BRANCH_PREDICTOR_TYPE}",
        f"mispredict_penalty = {branch_mispredict_penalty or DEFAULT_BRANCH_MISPREDICT_PENALTY}",
        f"size = {branch_predictor_size or DEFAULT_BRANCH_PREDICTOR_SIZE}",
        "",
    ])


def run(config: str, sniper: Path, outputdir: Path, cmd: list[str]) -> tuple[float, float, float]:
    forwarded: list[str] = [str(sniper), "-d", str(outputdir), "--power", "-c", config]

    if cmd[:1] == ["--"]:
        forwarded.extend(cmd[1:])
    else:
        forwarded.extend(cmd)

    env = os.environ.copy()
    env.setdefault("SNIPER_ROOT", str(ROOT / "snipersim"))

    result = subprocess.run([sys.executable, *forwarded], env=env, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Sniper failed with code {result.returncode}: {result.stderr}")

    power_file = Path(outputdir) / "power.txt"
    if not power_file.exists():
        raise FileNotFoundError(f"missing power report: {power_file}")

    area = None
    peak_power = None
    in_processor_section = False

    for raw_line in power_file.read_text(encoding="utf-8").splitlines():
        if raw_line.startswith("  ") and not raw_line.startswith("   "):
            line = raw_line.strip()
            if in_processor_section:
                if area is None and line.startswith("Area = ") and line.endswith("mm^2"):
                    area = float(line.split("=", 1)[1].split("mm^2")[0].strip())
                elif peak_power is None and line.startswith("Peak Power = ") and line.endswith("W"):
                    peak_power = float(line.split("=", 1)[1].split("W")[0].strip())
                if area is not None and peak_power is not None:
                    break
        if raw_line.strip() == "Processor:":
            in_processor_section = True

    if area is None or peak_power is None:
        raise ValueError(f"Could not extract Area or Peak Power from {power_file}")

    sniper_out = Path(outputdir) / "sim.out"
    if not sniper_out.exists():
        raise FileNotFoundError(f"missing sniper output: {sniper_out}")

    time = None
    for raw_line in sniper_out.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("Time (ns)"):
            time_str = line.split("|", 1)[1].strip()
            try:
                time = float(time_str)
            except ValueError:
                raise ValueError(f"Could not parse Time value: {time_str}")
            break

    if time is None:
        raise ValueError(f"Could not extract Time from {sniper_out}")

    return area, peak_power, time

@dataclass
class DesignPoint:
    """One evaluated design point."""
    params: dict[str, Any]      # overrides from baseline, e.g. {"l3_size": 4096}
    area: float                 # mm^2
    peak_power: float           # W
    time: float                 # ns
    asi: float = 0.0
    speedup: float = 0.0
    # which parameters have already been modified (not to be varied again in children)
    modified_params: set[str] = field(default_factory=set)


# Search space: for each parameter, the candidate values to try.
PARAM_SPACE: dict[str, list[Any]] = {
    "l1i_size":                 [16, 32, 64],
    "l1d_size":                 [16, 32, 64],
    "l2_size":                  [128, 256, 512],
    #"l3_size":                  [1024, 2048, 4096, 8192],
    #"l1i_assoc":                [4, 8],
    #"l1d_assoc":                [4, 8],
    #"l2_assoc":                 [4, 8],
    #"l3_assoc":                 [8, 16],
    #"branch_predictor_size":    [512, 1024, 2048],
}


def dominates(a: DesignPoint, b: DesignPoint) -> bool:
    """Return True if a dominates b (better or equal on both objectives,
    strictly better on at least one)."""
    return (
        a.asi >= b.asi and a.speedup >= b.speedup
        and (a.asi > b.asi or a.speedup > b.speedup)
    )


def update_pareto_front(
    front: list[DesignPoint],
    candidates: list[DesignPoint],
) -> list[DesignPoint]:
    """Recompute the Pareto front from front + candidates combined."""
    all_points = front + candidates
    return [
        p for p in all_points
        if not any(dominates(other, p) for other in all_points if other is not p)
    ]


def params_key(params: dict[str, Any]) -> frozenset:
    """Hashable representation of a config for deduplication."""
    return frozenset(params.items())


def evaluate_point(
    params: dict[str, Any],
    modified_params: set[str],
    label: str,
    reference_config: str,
    sniper: Path,
    outputdir: Path,
    cmd: list[str],
    baseline: DesignPoint,
    alpha: float,
) -> DesignPoint | None:
    """Write config, run Sniper, compute ASI and speedup, return DesignPoint."""
    cfg_path = outputdir / f"{label}.cfg"
    cfg_path.write_text(build_runtime_config(reference_config, **params), encoding="utf-8")
    try:
        area, peak_power, time = run(str(cfg_path), sniper, outputdir, cmd)
    except Exception as exc:
        print(f"  FAILED ({label}): {exc}")
        return None

    point = DesignPoint(
        params=params,
        area=area,
        peak_power=peak_power,
        time=time,
        modified_params=modified_params,
    )
    point.asi = calculate_asi(
        Ay=baseline.area,
        Ax=point.area,
        Py=baseline.peak_power,
        Px=point.peak_power,
        alpha=alpha,
    )
    point.speedup = baseline.time / point.time
    return point

def explore_pareto_front(
    reference_config: str,
    sniper: Path,
    outputdir: Path,
    cmd: list[str],
    alpha: float = DEFAULT_ALPHA,
    max_iterations: int = 3,
) -> list[DesignPoint]:
    """
    Iterative one-parameter-at-a-time exploration as described in Section V-B
    of the ASI paper.

    Three sets are maintained:
      - pareto_set:    current Pareto-optimal points
      - search_set:    configs pending evaluation this iteration
      - discarded_set: all evaluated non-Pareto configs (for deduplication)

    Returns the final Pareto front as a list of DesignPoints.
    """
    # 0. Evaluate baseline
    print("Running baseline...")
    baseline_cfg = outputdir / "baseline.cfg"
    baseline_cfg.write_text(build_runtime_config(reference_config), encoding="utf-8")
    try:
        area, peak_power, time = run(str(baseline_cfg), sniper, outputdir, cmd)
    except Exception as exc:
        raise RuntimeError(f"Baseline run failed: {exc}") from exc

    baseline = DesignPoint(
        params={},
        area=area,
        peak_power=peak_power,
        time=time,
        asi=1.0,
        speedup=1.0,
        modified_params=set(),
    )
    print(f"  Area={baseline.area:.4f} mm^2  "
          f"PeakPower={baseline.peak_power:.4f} W  "
          f"Time={baseline.time:.2f} ns")

    # 1. Initialise sets
    pareto_set: list[DesignPoint] = [baseline]
    discarded_set: set[frozenset] = set()
    # newly_added tracks which points were just added to pareto_set and should
    # generate children in the next iteration (starts as just the baseline)
    newly_added: list[DesignPoint] = [baseline]

    run_counter = 0

    for iteration in range(max_iterations):
        print(f"\n=== Iteration {iteration} ===")

        # 2. Generate search_set from newly added Pareto points
        search_set: list[tuple[dict[str, Any], set[str]]] = []  # (params, modified)

        for parent in newly_added:
            for param, values in PARAM_SPACE.items():
                # Only vary parameters not already modified in this lineage
                if param in parent.modified_params:
                    continue
                for value in values:
                    # Skip the default value for this param (no change)
                    default_value = {
                        "l1i_size": DEFAULT_L1I_SIZE,
                        "l1d_size": DEFAULT_L1D_SIZE,
                        "l2_size":  DEFAULT_L2_SIZE,
                        "l3_size":  DEFAULT_L3_SIZE,
                        "l1i_assoc": DEFAULT_L1I_ASSOC,
                        "l1d_assoc": DEFAULT_L1D_ASSOC,
                        "l2_assoc":  DEFAULT_L2_ASSOC,
                        "l3_assoc":  DEFAULT_L3_ASSOC,
                        "branch_predictor_size": DEFAULT_BRANCH_PREDICTOR_SIZE,
                    }.get(param)
                    if value == default_value and param not in parent.params:
                        continue  # this would be identical to the parent

                    child_params = {**parent.params, param: value}
                    child_modified = parent.modified_params | {param}
                    key = params_key(child_params)

                    # Skip if already evaluated (in Pareto or discarded)
                    already_in_pareto = any(
                        params_key(p.params) == key for p in pareto_set
                    )
                    if key in discarded_set or already_in_pareto:
                        continue

                    search_set.append((child_params, child_modified))

        if not search_set:
            print("  Search set is empty — converged.")
            break

        # 3. Evaluate search_set
        evaluated: list[DesignPoint] = []
        for i, (params, modified) in enumerate(search_set):
            label = f"iter{iteration}_run{i}"
            print(f"  {label}: {params}")
            point = evaluate_point(
                params=params,
                modified_params=modified,
                label=label,
                reference_config=reference_config,
                sniper=sniper,
                outputdir=outputdir,
                cmd=cmd,
                baseline=baseline,
                alpha=alpha,
            )
            if point is not None:
                run_counter += 1
                print(f"    ASI={point.asi:.4f}  Speedup={point.speedup:.4f}  "
                      f"Area={point.area:.4f}  PeakPower={point.peak_power:.4f}")
                evaluated.append(point)

        # 4. Update Pareto front
        new_pareto = update_pareto_front(pareto_set, evaluated)

        # Determine which points are newly on the front
        old_keys = {params_key(p.params) for p in pareto_set}
        newly_added = [p for p in new_pareto if params_key(p.params) not in old_keys]

        # Everything evaluated but not on the new front goes to discarded
        new_pareto_keys = {params_key(p.params) for p in new_pareto}
        for p in evaluated:
            if params_key(p.params) not in new_pareto_keys:
                discarded_set.add(params_key(p.params))

        pareto_set = new_pareto
        print(f"  Pareto front size: {len(pareto_set)}  "
              f"({len(newly_added)} new points added)")

    print(f"\nExploration complete. Total Sniper runs: {run_counter + 1} (including baseline)")
    return pareto_set

def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    sniper = Path(args.sniper).expanduser().resolve()
    if not sniper.exists():
        parser.error(f"run-sniper not found: {sniper}")

    outputdir = Path(args.outputdir).expanduser().resolve()
    outputdir.mkdir(parents=True, exist_ok=True)

    front = explore_pareto_front(
        reference_config=args.config,
        sniper=sniper,
        outputdir=outputdir,
        cmd=args.cmd,
        alpha=args.alpha,
        max_iterations=10,
    )

    print("\n=== Final Pareto Front ===")
    print(f"{'Params':<55} {'ASI':>8} {'Speedup':>10} {'Area':>10} {'PeakPow':>10}")
    print("-" * 100)
    for p in sorted(front, key=lambda x: x.speedup):
        print(f"{str(p.params):<55} {p.asi:>8.4f} {p.speedup:>10.4f} "
              f"{p.area:>10.4f} {p.peak_power:>10.4f}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())