#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
import subprocess
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
RUN_SNIPER = ROOT / "snipersim" / "run-sniper"
DEFAULT_OUTPUT_DIR = ROOT / "asi-output"
DEFAULT_CORE_MODEL = "nehalem"
DEFAULT_CORE_TYPE = "rob"
DEFAULT_FREQUENCY = 2.66
DEFAULT_LOGICAL_CPUS = 1
DEFAULT_L1I_SIZE = 32
DEFAULT_L1D_SIZE = 32
DEFAULT_L2_SIZE = 256
DEFAULT_L3_SIZE = 8192
DEFAULT_L1I_ASSOC = 4
DEFAULT_L1D_ASSOC = 8
DEFAULT_L2_ASSOC = 8
DEFAULT_L3_ASSOC = 16
DEFAULT_BRANCH_PREDICTOR_TYPE = "pentium_m"
DEFAULT_BRANCH_MISPREDICT_PENALTY = 8
DEFAULT_BRANCH_PREDICTOR_SIZE = 1024

# Alpha controls the area/power trade-off in the ASI formula
DEFAULT_ALPHA = 0.5

# Search space: each entry is a dict of keyword overrides for build_runtime_config.
# Add or remove candidates here to expand/shrink the exploration.
SEARCH_SPACE: list[dict[str, Any]] = [
    {},  # baseline itself (will be skipped during search, but useful for reference)
    {"l1i_size": 64},
    {"l1i_size": 16},
    {"l1d_size": 64},
    {"l1d_size": 16},
    {"l2_size": 512},
    {"l2_size": 128},
    {"l3_size": 4096},
    {"l3_size": 2048},
    {"l3_size": 1024},
    {"branch_predictor_size": 2048},
    {"branch_predictor_size": 512},
    {"frequency": 3.2},
    {"frequency": 2.0},
    {"l1i_size": 64, "l1d_size": 64},
    {"l2_size": 512, "l3_size": 4096},
    {"frequency": 3.2, "l3_size": 4096},
]


@dataclass
class DesignPoint:
    """One evaluated design point."""
    params: dict[str, Any]          # overrides from SEARCH_SPACE
    area: float                     # mm^2
    peak_power: float               # W
    time: float                     # ns
    asi: float = 0.0                # computed after baseline is known
    speedup: float = 0.0            # computed after baseline is known
    on_pareto_front: bool = False


# y: the reference design
# x: the design under test
def calculate_asi(Ay: float, Ax: float, Py: float, Px: float, alpha: float) -> float:
    return (1 - alpha * (Ax / Ay)) / ((1 - alpha) * (Px / Py))


def dominates(a: DesignPoint, b: DesignPoint) -> bool:
    """Return True if a dominates b (better or equal on both, strictly better on at least one)."""
    return (
        a.asi >= b.asi and a.speedup >= b.speedup
        and (a.asi > b.asi or a.speedup > b.speedup)
    )


def pareto_front(points: list[DesignPoint]) -> list[DesignPoint]:
    """Return the subset of points that are not dominated by any other point."""
    front = []
    for candidate in points:
        if not any(dominates(other, candidate) for other in points if other is not candidate):
            candidate.on_pareto_front = True
            front.append(candidate)
    return front


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="asi.py",
        description="Algorithm launcher for design space exploration.",
    )
    parser.add_argument("--config", required=True, help="Reference design config file for Sniper.")
    parser.add_argument("--sniper", default=str(RUN_SNIPER), help="Path to the run-sniper entry point.")
    parser.add_argument("--outputdir", "-d", default=str(DEFAULT_OUTPUT_DIR), help="Output directory.")
    parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA, help="Alpha for ASI formula.")
    parser.add_argument("--show-config", action="store_true", help="Print config and exit.")
    parser.add_argument("cmd", nargs=argparse.REMAINDER, help="Command to run after --.")
    return parser


def build_runtime_config(
    reference_config: str,
    *,
    cores: int = None,
    core_model: str = None,
    core_type: str = None,
    frequency: float = None,
    logical_cpus: int = None,
    l1i_size: int = None,
    l1i_assoc: int = None,
    l1d_size: int = None,
    l1d_assoc: int = None,
    l2_size: int = None,
    l2_assoc: int = None,
    l3_size: int = None,
    l3_assoc: int = None,
    branch_predictor_type: str = None,
    branch_mispredict_penalty: int = None,
    branch_predictor_size: int = None,
) -> str:
    return "\n".join([
        "# Auto-generated by framework/asi.py",
        "#include base",
        "#include gainestown",
        "#include rob",
        f"# Reference config: {reference_config}",
        "",
        "[general]",
        f"total_cores = {cores or 1}",
        "",
        "[perf_model/core]",
        f"core_model = {core_model or DEFAULT_CORE_MODEL}",
        f"type = {core_type or DEFAULT_CORE_TYPE}",
        f"frequency = {frequency or DEFAULT_FREQUENCY}",
        f"logical_cpus = {logical_cpus or DEFAULT_LOGICAL_CPUS}",
        "",
        "[perf_model/l1_icache]",
        f"cache_size = {l1i_size or DEFAULT_L1I_SIZE}",
        f"associativity = {l1i_assoc or DEFAULT_L1I_ASSOC}",
        "",
        "[perf_model/l1_dcache]",
        f"cache_size = {l1d_size or DEFAULT_L1D_SIZE}",
        f"associativity = {l1d_assoc or DEFAULT_L1D_ASSOC}",
        "",
        "[perf_model/l2_cache]",
        f"cache_size = {l2_size or DEFAULT_L2_SIZE}",
        f"associativity = {l2_assoc or DEFAULT_L2_ASSOC}",
        "",
        "[perf_model/l3_cache]",
        f"cache_size = {l3_size or DEFAULT_L3_SIZE}",
        f"associativity = {l3_assoc or DEFAULT_L3_ASSOC}",
        "",
        "[perf_model/branch_predictor]",
        f"type = {branch_predictor_type or DEFAULT_BRANCH_PREDICTOR_TYPE}",
        f"mispredict_penalty = {branch_mispredict_penalty or DEFAULT_BRANCH_MISPREDICT_PENALTY}",
        f"size = {branch_predictor_size or DEFAULT_BRANCH_PREDICTOR_SIZE}",
        "",
    ])


def run(config: str, sniper: Path, outputdir: Path, cmd: list[str]) -> tuple[float, float, float]:
    forwarded: list[str] = [str(sniper), "-d", str(outputdir), "--power", "-c", config]

    if cmd[:1] == ["--"]:
        forwarded.extend(cmd[1:])
    else:
        forwarded.extend(cmd)

    env = os.environ.copy()
    env.setdefault("SNIPER_ROOT", str(ROOT / "snipersim"))

    result = subprocess.run([sys.executable, *forwarded], env=env, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Sniper failed with code {result.returncode}: {result.stderr}")

    power_file = Path(outputdir) / "power.txt"
    if not power_file.exists():
        raise FileNotFoundError(f"missing power report: {power_file}")

    area = None
    peak_power = None
    in_processor_section = False

    for raw_line in power_file.read_text(encoding="utf-8").splitlines():
        if raw_line.startswith("  ") and not raw_line.startswith("   "):
            line = raw_line.strip()
            if in_processor_section:
                if area is None and line.startswith("Area = ") and line.endswith("mm^2"):
                    area = float(line.split("=", 1)[1].split("mm^2")[0].strip())
                elif peak_power is None and line.startswith("Peak Power = ") and line.endswith("W"):
                    peak_power = float(line.split("=", 1)[1].split("W")[0].strip())
                if area is not None and peak_power is not None:
                    break
        if raw_line.strip() == "Processor:":
            in_processor_section = True

    if area is None or peak_power is None:
        raise ValueError(f"Could not extract Area or Peak Power from {power_file}")

    sniper_out = Path(outputdir) / "sim.out"
    if not sniper_out.exists():
        raise FileNotFoundError(f"missing sniper output: {sniper_out}")

    time = None
    for raw_line in sniper_out.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("Time (ns)"):
            time_str = line.split("|", 1)[1].strip()
            try:
                time = float(time_str)
            except ValueError:
                raise ValueError(f"Could not parse Time value: {time_str}")
            break

    if time is None:
        raise ValueError(f"Could not extract Time from {sniper_out}")

    return area, peak_power, time


def evaluate(
    params: dict[str, Any],
    label: str,
    reference_config: str,
    sniper: Path,
    outputdir: Path,
    cmd: list[str],
) -> DesignPoint:
    """Write config, run Sniper, return an unevaluated DesignPoint (asi/speedup set later)."""
    cfg_path = outputdir / f"{label}.cfg"
    cfg_path.write_text(build_runtime_config(reference_config, **params), encoding="utf-8")
    area, peak_power, time = run(str(cfg_path), sniper, outputdir, cmd)
    return DesignPoint(params=params, area=area, peak_power=peak_power, time=time)


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    sniper = Path(args.sniper).expanduser().resolve()
    if not sniper.exists():
        parser.error(f"run-sniper not found: {sniper}")

    outputdir = Path(args.outputdir).expanduser().resolve()
    outputdir.mkdir(parents=True, exist_ok=True)

    # 1. Run baseline
    print("Running baseline...")
    baseline = evaluate({}, "baseline", args.config, sniper, outputdir, args.cmd)
    baseline.asi = 1.0      # by definition
    baseline.speedup = 1.0
    print(f"  Area={baseline.area:.4f} mm^2  PeakPower={baseline.peak_power:.4f} W  Time={baseline.time:.2f} ns")

    # 2. Evaluate all candidate designs
    all_points: list[DesignPoint] = [baseline]

    for i, params in enumerate(SEARCH_SPACE):
        if not params:
            continue  # skip the empty-dict entry (that's the baseline)

        label = f"design_{i}"
        print(f"Running {label}: {params}")
        try:
            point = evaluate(params, label, args.config, sniper, outputdir, args.cmd)
        except Exception as exc:
            print(f"  FAILED: {exc}")
            continue

        # ASI: higher is better (more performance per area*power)
        point.asi = calculate_asi(
            Ay=baseline.area,
            Ax=point.area,
            Py=baseline.peak_power,
            Px=point.peak_power,
            alpha=args.alpha,
        )
        # Speedup: higher is better (lower time = faster)
        point.speedup = baseline.time / point.time

        print(f"  Area={point.area:.4f}  PeakPower={point.peak_power:.4f}  "
              f"Time={point.time:.2f}  ASI={point.asi:.4f}  Speedup={point.speedup:.4f}")
        all_points.append(point)

    # 3. Build Pareto front
    front = pareto_front(all_points)

    print("\n=== Pareto Front ===")
    print(f"{'Params':<45} {'ASI':>8} {'Speedup':>10} {'Area':>10} {'PeakPow':>10}")
    print("-" * 90)
    for p in sorted(front, key=lambda x: x.asi, reverse=True):
        print(f"{str(p.params):<45} {p.asi:>8.4f} {p.speedup:>10.4f} "
              f"{p.area:>10.4f} {p.peak_power:>10.4f}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())